/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 aws-logo.glb -o AwsLogo.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AwsLogo(props) {
  const { nodes, materials } = useGLTF('/aws-logo.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.045, 1.513, -0.258]} rotation={[-Math.PI / 2, 0, 0]} scale={0.487}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[593.304, 205.677, -20.264]} scale={[16067.461, 16067.46, 16067.46]}>
            <group position={[-0.032, -0.04, 0.002]} scale={0.5}>
              <mesh geometry={nodes.ArrowHead_Material001_0_1.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.ArrowHead_Material001_0_2.geometry} material={materials['Material.003']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/aws-logo.glb')
