/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 javascript-logo.glb -o JavaScriptLogo.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function JavaScriptLogo(props) {
  const { nodes, materials } = useGLTF('/javascript-logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} position={[-0.543, -0.5, -0.004]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
      <mesh geometry={nodes.Curve001.geometry} material={materials.SVGMat} position={[-0.543, -0.5, -0.004]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
    </group>
  )
}

useGLTF.preload('/javascript-logo.glb')
