/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 java-logo.glb -o JavaLogo.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function JavaLogo(props) {
  const { nodes, materials } = useGLTF('/java-logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.002']} position={[-2.573, 0.137, 0.001]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.001']} position={[-2.573, 0.137, 0.001]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Curve003.geometry} material={materials['SVGMat.002']} position={[-2.573, 0.137, 0.001]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Curve004.geometry} material={materials['SVGMat.001']} position={[-2.573, 0.137, 0.001]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Curve005.geometry} material={materials['SVGMat.002']} position={[-2.573, 0.137, 0.001]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Curve006.geometry} material={materials['SVGMat.001']} position={[-2.573, 0.137, 0.001]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/java-logo.glb')
