/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 kafka-logo.glb -o KafkaLogo.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function KafkaLogo(props) {
  const { nodes, materials } = useGLTF('/kafka-logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials.SVGMat} position={[-0.25, -0.5, 0]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
    </group>
  )
}

useGLTF.preload('/kafka-logo.glb')
