/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mysql-logo.glb -o MySQLLogo.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MySQLLogo(props) {
  const { nodes, materials } = useGLTF('/mysql-logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.001']} position={[-0.5, -0.5, 0]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
    </group>
  )
}

useGLTF.preload('/mysql-logo.glb')
