/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spring-boot-logo.glb -o SpringBootLogo.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SpringBootLogo(props) {
  const { nodes, materials } = useGLTF('/spring-boot-logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/spring-boot-logo.glb')
